modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="pladailyboss"
version="${file.jarVersion}"
displayName="Pla Daily Boss"
logoFile="examplemod.png"
credits="Thanks for this example mod goes to Java"
authors="pla_is_me"
description='''
Pla made this mod for adding daily boss to Minecraft.
'''
[[dependencies.pladailyboss]]
    modId="forge"
    mandatory=true
    versionRange="[40.2.21,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pladailyboss]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pladailyboss]]
    modId="ftbchunks"
    mandatory=true
    versionRange="[1802.3.5,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.pladailyboss]]
    modId="experimentalsettingsdisabler"
    mandatory=false
    versionRange="[4.0,)"
    ordering="NONE"
    side="BOTH"