org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.06.26-1.20.1
mod_id=dailyboss_bosses_of_mass_destruction
mod_name=Daily Boss x Bosses of Mass Destruction
mod_license=All Rights Reserved
mod_version=1.0
mod_group_id=com.pla.dailyboss_bosses_of_mass_destruction
mod_authors=pla_is_me
mod_description=Compatibility between Daily Boss and Bosses of Mass Destruction.